services:
  db:
    image: postgres:latest          # Официальный образ PostgreSQL
    container_name: postgres_69     # Имя вашего контейнера
    restart: always                 # Перезапускать при сбоях или рестарте системы
    environment:
      - POSTGRES_USER=${DB_USER}       # Логин администратора
      - POSTGRES_PASSWORD=${DB_PASSWORD} # Пароль администратора
      - POSTGRES_DB=${DB_NAME}     # Название базы данных при создании
    ports:
      - "5432:5432"                 # Проброс порта: [порт на хосте]:[порт в контейнере]
    volumes:
      - ./postgres_data:/var/lib/postgresql # Хранение данных вне контейнера
    env_file:
      - .env

volumes:
  postgres_data:                    # Именованный том для сохранения данных
  # Пробрасываем переменные окружения из файла .env (токены, пароли почты)


