services:
  db:
    image: postgres:latest
    container_name: postgres_69
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    env_file:
      - .env

  # --- НОВЫЙ БЛОК: Объектное хранилище ---
  minio:
    image: minio/minio:latest
    container_name: minio_storage
    restart: always
    ports:
      - "9000:9000"    # Порт для API (для кода Python)
      - "9001:9001"    # Порт для консоли (в браузере)
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}        # Логин (из .env или admin)
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD} # Пароль
    volumes:
      - ./minio_data:/data   # Данные будут лежать в папке minio_data рядом с проектом
    command: server /data --console-address ":9001"
    env_file:
      - .env

  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    env_file:
      - .env
    environment:
      # Важно: теперь приложение должно стучаться к db и minio
      # по именам сервисов в сети Docker, а не по localhost!
      - DB_HOST=db
      - MINIO_ENDPOINT=http://minio:9000


volumes:
  postgres_data:
  minio_data:      # Добавляем том для MinIO
